server:
  port: 8081

spring:
  ##thymeleaf:
  ##prefix: classpath:/static/
  ##suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/slackreact?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: springsecurity
    password: qwer1234

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE